---
ability_to_speak_english__spea.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
ability_to_speak_irish__popula.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
age_group__persons_with_disabi.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
age_group_gender__population.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: category2
  col6: count
  col7: description
central_heating__households.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
children_born_alive__females_a.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
children_over_15_in_family__fa.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
children_under_15_in_family__f.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
children_under_and_over_15_in_.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
ethnic_group__usually_resident.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
family_cycle__families.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
family_cycle__persons.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
frequency_of_speaking_irish__i.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
gender__communal_establishment.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
gender__persons_in_communal_es.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
gender_age_education_ceased__p.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: category2
  col6: count
  col7: description
gender_education_status__popul.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: category2
  col6: count
  col7: description
gender_field_of_study__populat.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: category2
  col6: count
  col7: description
gender_frequency_of_speaking_i.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: category2
  col6: count
  col7: description
gender_general_health_status__.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: category2
  col6: count
  col7: description
gender_highest_level_of_educat.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: category2
  col6: count
  col7: description
gender_industry__persons_at_wo.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: category2
  col6: count
  col7: description
gender_number_of_unpaid_hours_.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: category2
  col6: count
  col7: description
gender_occupation__persons.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: category2
  col6: count
  col7: description
gender_principal_economic_stat.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: category2
  col6: count
  col7: description
gender_social_class__populatio.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: category2
  col6: count
  col7: description
have_a_personal_computer__hous.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
household_size__households.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
household_size__persons.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
household_type__households.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
household_type__persons.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
household_year_built__househol.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
household_year_built__persons.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
internet__households.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
journey_time_to_work__school_o.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
language_spoken__speakers_of_f.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
marital_status_gender__populat.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: category2
  col6: count
  col7: description
means_of_travel_to_work__schoo.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
nationality__usually_resident_.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
number_of_motor_cars__househol.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
number_of_rooms__households.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
number_of_rooms__persons.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
occupancy_status_on_census_nig.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
place_of_birth__usually_reside.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
religion__population.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
sewerage_facility__households.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
size_of_family__children_.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
size_of_family__families.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
size_of_family__family_members.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
socio_economic_group_of_refere.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
time_leaving_home_to_travel_to.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
total_children_in_family__fami.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
type_of_accommodation__househo.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
type_of_accommodation__persons.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
type_of_family_children_age__c.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: category2
  col6: count
  col7: description
type_of_family_children_age__f.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: category2
  col6: count
  col7: description
type_of_occupancy__households.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
type_of_occupancy__persons.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
usual_residence_1_year_before_.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
water_supply__households.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
youngest_child_age_group__fami.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
youngest_child_age_group__pers.tsv:
  col1: location_code
  col2: location_type
  col3: location_label
  col4: category1
  col5: count
  col6: description
